const DEFAULT_BODY_ANIMATION_CYCLE_MS = 400;
const DEFAULT_WEAPON_ANIMATION_CYCLE_MS = 400;
const DEFAULT_SHIELD_ANIMATION_CYCLE_MS = 400;

export const BODY_ANIMATION_CYCLE_MS = DEFAULT_BODY_ANIMATION_CYCLE_MS;
export const WEAPON_ANIMATION_CYCLE_MS = DEFAULT_WEAPON_ANIMATION_CYCLE_MS;
export const SHIELD_ANIMATION_CYCLE_MS = DEFAULT_SHIELD_ANIMATION_CYCLE_MS;
