export const TILE_SIZE = 32;
export const VIEWPORT_TILE_RADIUS = 10;
export const VIEWPORT_TILE_WIDTH = VIEWPORT_TILE_RADIUS * 2 + 1;
export const VIEWPORT_TILE_HEIGHT = VIEWPORT_TILE_RADIUS * 2 + 1;
export const VIEWPORT_PIXEL_WIDTH = VIEWPORT_TILE_WIDTH * TILE_SIZE;
export const VIEWPORT_PIXEL_HEIGHT = VIEWPORT_TILE_HEIGHT * TILE_SIZE;
